//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.17 at 06:36:56 PM UTC 
//


package com.projektr.tomcatservertest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CountryEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CountryEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="at"/&gt;
 *     &lt;enumeration value="be"/&gt;
 *     &lt;enumeration value="bg"/&gt;
 *     &lt;enumeration value="ch"/&gt;
 *     &lt;enumeration value="cs"/&gt;
 *     &lt;enumeration value="cy"/&gt;
 *     &lt;enumeration value="cz"/&gt;
 *     &lt;enumeration value="de"/&gt;
 *     &lt;enumeration value="dk"/&gt;
 *     &lt;enumeration value="ee"/&gt;
 *     &lt;enumeration value="es"/&gt;
 *     &lt;enumeration value="fi"/&gt;
 *     &lt;enumeration value="fo"/&gt;
 *     &lt;enumeration value="fr"/&gt;
 *     &lt;enumeration value="gb"/&gt;
 *     &lt;enumeration value="gg"/&gt;
 *     &lt;enumeration value="gi"/&gt;
 *     &lt;enumeration value="gr"/&gt;
 *     &lt;enumeration value="hr"/&gt;
 *     &lt;enumeration value="hu"/&gt;
 *     &lt;enumeration value="ie"/&gt;
 *     &lt;enumeration value="im"/&gt;
 *     &lt;enumeration value="is"/&gt;
 *     &lt;enumeration value="it"/&gt;
 *     &lt;enumeration value="je"/&gt;
 *     &lt;enumeration value="li"/&gt;
 *     &lt;enumeration value="lt"/&gt;
 *     &lt;enumeration value="lu"/&gt;
 *     &lt;enumeration value="lv"/&gt;
 *     &lt;enumeration value="ma"/&gt;
 *     &lt;enumeration value="mc"/&gt;
 *     &lt;enumeration value="mk"/&gt;
 *     &lt;enumeration value="mt"/&gt;
 *     &lt;enumeration value="nl"/&gt;
 *     &lt;enumeration value="no"/&gt;
 *     &lt;enumeration value="pl"/&gt;
 *     &lt;enumeration value="pt"/&gt;
 *     &lt;enumeration value="ro"/&gt;
 *     &lt;enumeration value="se"/&gt;
 *     &lt;enumeration value="si"/&gt;
 *     &lt;enumeration value="sk"/&gt;
 *     &lt;enumeration value="sm"/&gt;
 *     &lt;enumeration value="tr"/&gt;
 *     &lt;enumeration value="va"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CountryEnum")
@XmlEnum
public enum CountryEnum {


    /**
     * Austria
     * 
     */
    @XmlEnumValue("at")
    AT("at"),

    /**
     * Belgium
     * 
     */
    @XmlEnumValue("be")
    BE("be"),

    /**
     * Bulgaria
     * 
     */
    @XmlEnumValue("bg")
    BG("bg"),

    /**
     * Switzerland
     * 
     */
    @XmlEnumValue("ch")
    CH("ch"),

    /**
     * Serbia and Montenegro
     * 
     */
    @XmlEnumValue("cs")
    CS("cs"),

    /**
     * Cyprus
     * 
     */
    @XmlEnumValue("cy")
    CY("cy"),

    /**
     * Czech Republic
     * 
     */
    @XmlEnumValue("cz")
    CZ("cz"),

    /**
     * Germany
     * 
     */
    @XmlEnumValue("de")
    DE("de"),

    /**
     * Denmark
     * 
     */
    @XmlEnumValue("dk")
    DK("dk"),

    /**
     * Estonia
     * 
     */
    @XmlEnumValue("ee")
    EE("ee"),

    /**
     * Spain
     * 
     */
    @XmlEnumValue("es")
    ES("es"),

    /**
     * Finland
     * 
     */
    @XmlEnumValue("fi")
    FI("fi"),

    /**
     * Faroe Islands
     * 
     */
    @XmlEnumValue("fo")
    FO("fo"),

    /**
     * France
     * 
     */
    @XmlEnumValue("fr")
    FR("fr"),

    /**
     * Great Britain
     * 
     */
    @XmlEnumValue("gb")
    GB("gb"),

    /**
     * Guernsey
     * 
     */
    @XmlEnumValue("gg")
    GG("gg"),

    /**
     * Gibraltar
     * 
     */
    @XmlEnumValue("gi")
    GI("gi"),

    /**
     * Greece
     * 
     */
    @XmlEnumValue("gr")
    GR("gr"),

    /**
     * Croatia
     * 
     */
    @XmlEnumValue("hr")
    HR("hr"),

    /**
     * Hungary
     * 
     */
    @XmlEnumValue("hu")
    HU("hu"),

    /**
     * Ireland
     * 
     */
    @XmlEnumValue("ie")
    IE("ie"),

    /**
     * Isle Of Man
     * 
     */
    @XmlEnumValue("im")
    IM("im"),

    /**
     * Iceland
     * 
     */
    @XmlEnumValue("is")
    IS("is"),

    /**
     * Italy
     * 
     */
    @XmlEnumValue("it")
    IT("it"),

    /**
     * Jersey
     * 
     */
    @XmlEnumValue("je")
    JE("je"),

    /**
     * Lichtenstein
     * 
     */
    @XmlEnumValue("li")
    LI("li"),

    /**
     * Lithuania
     * 
     */
    @XmlEnumValue("lt")
    LT("lt"),

    /**
     * Luxembourg
     * 
     */
    @XmlEnumValue("lu")
    LU("lu"),

    /**
     * Latvia
     * 
     */
    @XmlEnumValue("lv")
    LV("lv"),

    /**
     * Morocco
     * 
     */
    @XmlEnumValue("ma")
    MA("ma"),

    /**
     * Monaco
     * 
     */
    @XmlEnumValue("mc")
    MC("mc"),

    /**
     * Macedonia
     * 
     */
    @XmlEnumValue("mk")
    MK("mk"),

    /**
     * Malta
     * 
     */
    @XmlEnumValue("mt")
    MT("mt"),

    /**
     * Netherlands
     * 
     */
    @XmlEnumValue("nl")
    NL("nl"),

    /**
     * Norway
     * 
     */
    @XmlEnumValue("no")
    NO("no"),

    /**
     * Poland
     * 
     */
    @XmlEnumValue("pl")
    PL("pl"),

    /**
     * Portugal
     * 
     */
    @XmlEnumValue("pt")
    PT("pt"),

    /**
     * Romania
     * 
     */
    @XmlEnumValue("ro")
    RO("ro"),

    /**
     * Sweden
     * 
     */
    @XmlEnumValue("se")
    SE("se"),

    /**
     * Slovenia
     * 
     */
    @XmlEnumValue("si")
    SI("si"),

    /**
     * Slovakia
     * 
     */
    @XmlEnumValue("sk")
    SK("sk"),

    /**
     * San Marino
     * 
     */
    @XmlEnumValue("sm")
    SM("sm"),

    /**
     * Turkey
     * 
     */
    @XmlEnumValue("tr")
    TR("tr"),

    /**
     * Vatican City State
     * 
     */
    @XmlEnumValue("va")
    VA("va"),

    /**
     * Other than as defined in this enumeration.
     * 
     */
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    CountryEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CountryEnum fromValue(String v) {
        for (CountryEnum c: CountryEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
