//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.17 at 06:36:56 PM UTC 
//


package com.projektr.tomcatservertest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.projektr.tomcatservertest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _D2LogicalModel_QNAME = new QName("http://datex2.eu/schema/2/2_0", "d2LogicalModel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.projektr.tomcatservertest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MultilingualString }
     * 
     */
    public MultilingualString createMultilingualString() {
        return new MultilingualString();
    }

    /**
     * Create an instance of {@link D2LogicalModel }
     * 
     */
    public D2LogicalModel createD2LogicalModel() {
        return new D2LogicalModel();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link PointExtensionType }
     * 
     */
    public PointExtensionType createPointExtensionType() {
        return new PointExtensionType();
    }

    /**
     * Create an instance of {@link PredefinedLocationContainerExtensionType }
     * 
     */
    public PredefinedLocationContainerExtensionType createPredefinedLocationContainerExtensionType() {
        return new PredefinedLocationContainerExtensionType();
    }

    /**
     * Create an instance of {@link AffectedCarriagewayAndLanes }
     * 
     */
    public AffectedCarriagewayAndLanes createAffectedCarriagewayAndLanes() {
        return new AffectedCarriagewayAndLanes();
    }

    /**
     * Create an instance of {@link AlertCDirection }
     * 
     */
    public AlertCDirection createAlertCDirection() {
        return new AlertCDirection();
    }

    /**
     * Create an instance of {@link AlertCLocation }
     * 
     */
    public AlertCLocation createAlertCLocation() {
        return new AlertCLocation();
    }

    /**
     * Create an instance of {@link AlertCMethod4Point }
     * 
     */
    public AlertCMethod4Point createAlertCMethod4Point() {
        return new AlertCMethod4Point();
    }

    /**
     * Create an instance of {@link AlertCMethod4PrimaryPointLocation }
     * 
     */
    public AlertCMethod4PrimaryPointLocation createAlertCMethod4PrimaryPointLocation() {
        return new AlertCMethod4PrimaryPointLocation();
    }

    /**
     * Create an instance of {@link DistanceFromLinearElementStart }
     * 
     */
    public DistanceFromLinearElementStart createDistanceFromLinearElementStart() {
        return new DistanceFromLinearElementStart();
    }

    /**
     * Create an instance of {@link Exchange }
     * 
     */
    public Exchange createExchange() {
        return new Exchange();
    }

    /**
     * Create an instance of {@link HeaderInformation }
     * 
     */
    public HeaderInformation createHeaderInformation() {
        return new HeaderInformation();
    }

    /**
     * Create an instance of {@link InternationalIdentifier }
     * 
     */
    public InternationalIdentifier createInternationalIdentifier() {
        return new InternationalIdentifier();
    }

    /**
     * Create an instance of {@link LinearElement }
     * 
     */
    public LinearElement createLinearElement() {
        return new LinearElement();
    }

    /**
     * Create an instance of {@link LinearElementByCode }
     * 
     */
    public LinearElementByCode createLinearElementByCode() {
        return new LinearElementByCode();
    }

    /**
     * Create an instance of {@link MultilingualStringValue }
     * 
     */
    public MultilingualStringValue createMultilingualStringValue() {
        return new MultilingualStringValue();
    }

    /**
     * Create an instance of {@link OffsetDistance }
     * 
     */
    public OffsetDistance createOffsetDistance() {
        return new OffsetDistance();
    }

    /**
     * Create an instance of {@link OpenlrExtendedPoint }
     * 
     */
    public OpenlrExtendedPoint createOpenlrExtendedPoint() {
        return new OpenlrExtendedPoint();
    }

    /**
     * Create an instance of {@link OpenlrGeoCoordinate }
     * 
     */
    public OpenlrGeoCoordinate createOpenlrGeoCoordinate() {
        return new OpenlrGeoCoordinate();
    }

    /**
     * Create an instance of {@link OpenlrLastLocationReferencePoint }
     * 
     */
    public OpenlrLastLocationReferencePoint createOpenlrLastLocationReferencePoint() {
        return new OpenlrLastLocationReferencePoint();
    }

    /**
     * Create an instance of {@link OpenlrLineAttributes }
     * 
     */
    public OpenlrLineAttributes createOpenlrLineAttributes() {
        return new OpenlrLineAttributes();
    }

    /**
     * Create an instance of {@link OpenlrLocationReferencePoint }
     * 
     */
    public OpenlrLocationReferencePoint createOpenlrLocationReferencePoint() {
        return new OpenlrLocationReferencePoint();
    }

    /**
     * Create an instance of {@link OpenlrPathAttributes }
     * 
     */
    public OpenlrPathAttributes createOpenlrPathAttributes() {
        return new OpenlrPathAttributes();
    }

    /**
     * Create an instance of {@link OpenlrPointAlongLine }
     * 
     */
    public OpenlrPointAlongLine createOpenlrPointAlongLine() {
        return new OpenlrPointAlongLine();
    }

    /**
     * Create an instance of {@link OpenlrPointLocationReference }
     * 
     */
    public OpenlrPointLocationReference createOpenlrPointLocationReference() {
        return new OpenlrPointLocationReference();
    }

    /**
     * Create an instance of {@link OpenlrPoiWithAccessPoint }
     * 
     */
    public OpenlrPoiWithAccessPoint createOpenlrPoiWithAccessPoint() {
        return new OpenlrPoiWithAccessPoint();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link PointAlongLinearElement }
     * 
     */
    public PointAlongLinearElement createPointAlongLinearElement() {
        return new PointAlongLinearElement();
    }

    /**
     * Create an instance of {@link PointByCoordinates }
     * 
     */
    public PointByCoordinates createPointByCoordinates() {
        return new PointByCoordinates();
    }

    /**
     * Create an instance of {@link PointCoordinates }
     * 
     */
    public PointCoordinates createPointCoordinates() {
        return new PointCoordinates();
    }

    /**
     * Create an instance of {@link PredefinedLocation }
     * 
     */
    public PredefinedLocation createPredefinedLocation() {
        return new PredefinedLocation();
    }

    /**
     * Create an instance of {@link PredefinedLocationsPublication }
     * 
     */
    public PredefinedLocationsPublication createPredefinedLocationsPublication() {
        return new PredefinedLocationsPublication();
    }

    /**
     * Create an instance of {@link SupplementaryPositionalDescription }
     * 
     */
    public SupplementaryPositionalDescription createSupplementaryPositionalDescription() {
        return new SupplementaryPositionalDescription();
    }

    /**
     * Create an instance of {@link TrafficCameraRecord }
     * 
     */
    public TrafficCameraRecord createTrafficCameraRecord() {
        return new TrafficCameraRecord();
    }

    /**
     * Create an instance of {@link MultilingualString.Values }
     * 
     */
    public MultilingualString.Values createMultilingualStringValues() {
        return new MultilingualString.Values();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link D2LogicalModel }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link D2LogicalModel }{@code >}
     */
    @XmlElementDecl(namespace = "http://datex2.eu/schema/2/2_0", name = "d2LogicalModel")
    public JAXBElement<D2LogicalModel> createD2LogicalModel(D2LogicalModel value) {
        return new JAXBElement<D2LogicalModel>(_D2LogicalModel_QNAME, D2LogicalModel.class, null, value);
    }

}
