//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.17 at 06:36:56 PM UTC 
//


package com.projektr.tomcatservertest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpenlrFormOfWayEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OpenlrFormOfWayEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="undefined"/&gt;
 *     &lt;enumeration value="motorway"/&gt;
 *     &lt;enumeration value="multipleCarriageway"/&gt;
 *     &lt;enumeration value="singleCarriageway"/&gt;
 *     &lt;enumeration value="roundabout"/&gt;
 *     &lt;enumeration value="slipRoad"/&gt;
 *     &lt;enumeration value="trafficSquare"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OpenlrFormOfWayEnum")
@XmlEnum
public enum OpenlrFormOfWayEnum {


    /**
     * undefined
     * 
     */
    @XmlEnumValue("undefined")
    UNDEFINED("undefined"),

    /**
     * motorway
     * 
     */
    @XmlEnumValue("motorway")
    MOTORWAY("motorway"),

    /**
     * multipleCarrigeway
     * 
     */
    @XmlEnumValue("multipleCarriageway")
    MULTIPLE_CARRIAGEWAY("multipleCarriageway"),

    /**
     * single carrigeway
     * 
     */
    @XmlEnumValue("singleCarriageway")
    SINGLE_CARRIAGEWAY("singleCarriageway"),

    /**
     * roadabout
     * 
     */
    @XmlEnumValue("roundabout")
    ROUNDABOUT("roundabout"),

    /**
     * sliproad
     * 
     */
    @XmlEnumValue("slipRoad")
    SLIP_ROAD("slipRoad"),

    /**
     * traffic square
     * 
     */
    @XmlEnumValue("trafficSquare")
    TRAFFIC_SQUARE("trafficSquare"),

    /**
     * other
     * 
     */
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    OpenlrFormOfWayEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OpenlrFormOfWayEnum fromValue(String v) {
        for (OpenlrFormOfWayEnum c: OpenlrFormOfWayEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
