//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.17 at 06:36:56 PM UTC 
//


package com.projektr.tomcatservertest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpenlrOrientationEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OpenlrOrientationEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="noOrientationOrUnknown"/&gt;
 *     &lt;enumeration value="withLineDirection"/&gt;
 *     &lt;enumeration value="againstLineDirection"/&gt;
 *     &lt;enumeration value="both"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OpenlrOrientationEnum")
@XmlEnum
public enum OpenlrOrientationEnum {


    /**
     * No orientation or unknown
     * 
     */
    @XmlEnumValue("noOrientationOrUnknown")
    NO_ORIENTATION_OR_UNKNOWN("noOrientationOrUnknown"),

    /**
     * With line direction
     * 
     */
    @XmlEnumValue("withLineDirection")
    WITH_LINE_DIRECTION("withLineDirection"),

    /**
     * Against line direction
     * 
     */
    @XmlEnumValue("againstLineDirection")
    AGAINST_LINE_DIRECTION("againstLineDirection"),

    /**
     * Both directions
     * 
     */
    @XmlEnumValue("both")
    BOTH("both");
    private final String value;

    OpenlrOrientationEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OpenlrOrientationEnum fromValue(String v) {
        for (OpenlrOrientationEnum c: OpenlrOrientationEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
