//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.17 at 06:36:56 PM UTC 
//


package com.projektr.tomcatservertest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrafficCameraTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TrafficCameraTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="analog"/&gt;
 *     &lt;enumeration value="digital"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TrafficCameraTypeEnum")
@XmlEnum
public enum TrafficCameraTypeEnum {


    /**
     * Camera is analog
     * 
     */
    @XmlEnumValue("analog")
    ANALOG("analog"),

    /**
     * Camera is digital
     * 
     */
    @XmlEnumValue("digital")
    DIGITAL("digital");
    private final String value;

    TrafficCameraTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TrafficCameraTypeEnum fromValue(String v) {
        for (TrafficCameraTypeEnum c: TrafficCameraTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
