//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.17 at 06:36:56 PM UTC 
//


package com.projektr.tomcatservertest;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * RealisCameras extension type
 * 
 * <p>Java class for TrafficCameraRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrafficCameraRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cameraId" type="{http://datex2.eu/schema/2/2_0}String"/&gt;
 *         &lt;element name="updatedTS" type="{http://datex2.eu/schema/2/2_0}DateTime" minOccurs="0"/&gt;
 *         &lt;element name="stillImageUrl" type="{http://datex2.eu/schema/2/2_0}Url" minOccurs="0"/&gt;
 *         &lt;element name="stillImageContentType" type="{http://datex2.eu/schema/2/2_0}String" minOccurs="0"/&gt;
 *         &lt;element name="stillImageHeight" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="stillImageWidth" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="stillImageRefreshIntervalMS" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="videoUrl" type="{http://datex2.eu/schema/2/2_0}Url" minOccurs="0"/&gt;
 *         &lt;element name="videoContentType" type="{http://datex2.eu/schema/2/2_0}String" minOccurs="0"/&gt;
 *         &lt;element name="videoHeight" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="videoWidth" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="videoFrameRate" type="{http://datex2.eu/schema/2/2_0}Float" minOccurs="0"/&gt;
 *         &lt;element name="viewBearing" type="{http://datex2.eu/schema/2/2_0}AngleInDegrees" minOccurs="0"/&gt;
 *         &lt;element name="viewAngle" type="{http://datex2.eu/schema/2/2_0}AngleInDegrees" minOccurs="0"/&gt;
 *         &lt;element name="zoom" type="{http://datex2.eu/schema/2/2_0}Float" minOccurs="0"/&gt;
 *         &lt;element name="heightMeters" type="{http://datex2.eu/schema/2/2_0}Float" minOccurs="0"/&gt;
 *         &lt;element name="cameraTitle" type="{http://datex2.eu/schema/2/2_0}MultilingualString" minOccurs="0"/&gt;
 *         &lt;element name="cameraDescription" type="{http://datex2.eu/schema/2/2_0}MultilingualString" minOccurs="0"/&gt;
 *         &lt;element name="groupId" type="{http://datex2.eu/schema/2/2_0}String" minOccurs="0"/&gt;
 *         &lt;element name="groupName" type="{http://datex2.eu/schema/2/2_0}MultilingualString" minOccurs="0"/&gt;
 *         &lt;element name="regionName" type="{http://datex2.eu/schema/2/2_0}MultilingualString" minOccurs="0"/&gt;
 *         &lt;element name="cameraType" type="{http://datex2.eu/schema/2/2_0}TrafficCameraTypeEnum" minOccurs="0"/&gt;
 *         &lt;element name="visibility" type="{http://datex2.eu/schema/2/2_0}TrafficCameraVisibilityEnum" minOccurs="0"/&gt;
 *         &lt;element name="cameraCapabilities" type="{http://datex2.eu/schema/2/2_0}TrafficCameraCapabilityEnum" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="priority" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="previousCameraId" type="{http://datex2.eu/schema/2/2_0}String" minOccurs="0"/&gt;
 *         &lt;element name="nextCameraId" type="{http://datex2.eu/schema/2/2_0}String" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrafficCameraRecord", propOrder = {
    "cameraId",
    "updatedTS",
    "stillImageUrl",
    "stillImageContentType",
    "stillImageHeight",
    "stillImageWidth",
    "stillImageRefreshIntervalMS",
    "videoUrl",
    "videoContentType",
    "videoHeight",
    "videoWidth",
    "videoFrameRate",
    "viewBearing",
    "viewAngle",
    "zoom",
    "heightMeters",
    "cameraTitle",
    "cameraDescription",
    "groupId",
    "groupName",
    "regionName",
    "cameraType",
    "visibility",
    "cameraCapabilities",
    "priority",
    "previousCameraId",
    "nextCameraId"
})
public class TrafficCameraRecord {

    @XmlElement(required = true)
    protected String cameraId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedTS;
    @XmlSchemaType(name = "anyURI")
    protected String stillImageUrl;
    protected String stillImageContentType;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger stillImageHeight;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger stillImageWidth;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger stillImageRefreshIntervalMS;
    @XmlSchemaType(name = "anyURI")
    protected String videoUrl;
    protected String videoContentType;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger videoHeight;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger videoWidth;
    protected Float videoFrameRate;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger viewBearing;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger viewAngle;
    protected Float zoom;
    protected Float heightMeters;
    protected MultilingualString cameraTitle;
    protected MultilingualString cameraDescription;
    protected String groupId;
    protected MultilingualString groupName;
    protected MultilingualString regionName;
    @XmlSchemaType(name = "string")
    protected TrafficCameraTypeEnum cameraType;
    @XmlSchemaType(name = "string")
    protected TrafficCameraVisibilityEnum visibility;
    @XmlSchemaType(name = "string")
    protected List<TrafficCameraCapabilityEnum> cameraCapabilities;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger priority;
    protected String previousCameraId;
    protected String nextCameraId;

    /**
     * Gets the value of the cameraId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCameraId() {
        return cameraId;
    }

    /**
     * Sets the value of the cameraId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCameraId(String value) {
        this.cameraId = value;
    }

    /**
     * Gets the value of the updatedTS property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedTS() {
        return updatedTS;
    }

    /**
     * Sets the value of the updatedTS property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedTS(XMLGregorianCalendar value) {
        this.updatedTS = value;
    }

    /**
     * Gets the value of the stillImageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStillImageUrl() {
        return stillImageUrl;
    }

    /**
     * Sets the value of the stillImageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStillImageUrl(String value) {
        this.stillImageUrl = value;
    }

    /**
     * Gets the value of the stillImageContentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStillImageContentType() {
        return stillImageContentType;
    }

    /**
     * Sets the value of the stillImageContentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStillImageContentType(String value) {
        this.stillImageContentType = value;
    }

    /**
     * Gets the value of the stillImageHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStillImageHeight() {
        return stillImageHeight;
    }

    /**
     * Sets the value of the stillImageHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStillImageHeight(BigInteger value) {
        this.stillImageHeight = value;
    }

    /**
     * Gets the value of the stillImageWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStillImageWidth() {
        return stillImageWidth;
    }

    /**
     * Sets the value of the stillImageWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStillImageWidth(BigInteger value) {
        this.stillImageWidth = value;
    }

    /**
     * Gets the value of the stillImageRefreshIntervalMS property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStillImageRefreshIntervalMS() {
        return stillImageRefreshIntervalMS;
    }

    /**
     * Sets the value of the stillImageRefreshIntervalMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStillImageRefreshIntervalMS(BigInteger value) {
        this.stillImageRefreshIntervalMS = value;
    }

    /**
     * Gets the value of the videoUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * Sets the value of the videoUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoUrl(String value) {
        this.videoUrl = value;
    }

    /**
     * Gets the value of the videoContentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoContentType() {
        return videoContentType;
    }

    /**
     * Sets the value of the videoContentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoContentType(String value) {
        this.videoContentType = value;
    }

    /**
     * Gets the value of the videoHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVideoHeight() {
        return videoHeight;
    }

    /**
     * Sets the value of the videoHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVideoHeight(BigInteger value) {
        this.videoHeight = value;
    }

    /**
     * Gets the value of the videoWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVideoWidth() {
        return videoWidth;
    }

    /**
     * Sets the value of the videoWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVideoWidth(BigInteger value) {
        this.videoWidth = value;
    }

    /**
     * Gets the value of the videoFrameRate property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVideoFrameRate() {
        return videoFrameRate;
    }

    /**
     * Sets the value of the videoFrameRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVideoFrameRate(Float value) {
        this.videoFrameRate = value;
    }

    /**
     * Gets the value of the viewBearing property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getViewBearing() {
        return viewBearing;
    }

    /**
     * Sets the value of the viewBearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setViewBearing(BigInteger value) {
        this.viewBearing = value;
    }

    /**
     * Gets the value of the viewAngle property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getViewAngle() {
        return viewAngle;
    }

    /**
     * Sets the value of the viewAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setViewAngle(BigInteger value) {
        this.viewAngle = value;
    }

    /**
     * Gets the value of the zoom property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getZoom() {
        return zoom;
    }

    /**
     * Sets the value of the zoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setZoom(Float value) {
        this.zoom = value;
    }

    /**
     * Gets the value of the heightMeters property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getHeightMeters() {
        return heightMeters;
    }

    /**
     * Sets the value of the heightMeters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setHeightMeters(Float value) {
        this.heightMeters = value;
    }

    /**
     * Gets the value of the cameraTitle property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getCameraTitle() {
        return cameraTitle;
    }

    /**
     * Sets the value of the cameraTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setCameraTitle(MultilingualString value) {
        this.cameraTitle = value;
    }

    /**
     * Gets the value of the cameraDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getCameraDescription() {
        return cameraDescription;
    }

    /**
     * Sets the value of the cameraDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setCameraDescription(MultilingualString value) {
        this.cameraDescription = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setGroupName(MultilingualString value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the regionName property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getRegionName() {
        return regionName;
    }

    /**
     * Sets the value of the regionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setRegionName(MultilingualString value) {
        this.regionName = value;
    }

    /**
     * Gets the value of the cameraType property.
     * 
     * @return
     *     possible object is
     *     {@link TrafficCameraTypeEnum }
     *     
     */
    public TrafficCameraTypeEnum getCameraType() {
        return cameraType;
    }

    /**
     * Sets the value of the cameraType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrafficCameraTypeEnum }
     *     
     */
    public void setCameraType(TrafficCameraTypeEnum value) {
        this.cameraType = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link TrafficCameraVisibilityEnum }
     *     
     */
    public TrafficCameraVisibilityEnum getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrafficCameraVisibilityEnum }
     *     
     */
    public void setVisibility(TrafficCameraVisibilityEnum value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the cameraCapabilities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cameraCapabilities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCameraCapabilities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrafficCameraCapabilityEnum }
     * 
     * 
     */
    public List<TrafficCameraCapabilityEnum> getCameraCapabilities() {
        if (cameraCapabilities == null) {
            cameraCapabilities = new ArrayList<TrafficCameraCapabilityEnum>();
        }
        return this.cameraCapabilities;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority(BigInteger value) {
        this.priority = value;
    }

    /**
     * Gets the value of the previousCameraId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousCameraId() {
        return previousCameraId;
    }

    /**
     * Sets the value of the previousCameraId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousCameraId(String value) {
        this.previousCameraId = value;
    }

    /**
     * Gets the value of the nextCameraId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextCameraId() {
        return nextCameraId;
    }

    /**
     * Sets the value of the nextCameraId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextCameraId(String value) {
        this.nextCameraId = value;
    }

}
