//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.17 at 06:36:56 PM UTC 
//


package com.projektr.tomcatservertest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrafficCameraCapabilityEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TrafficCameraCapabilityEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="canPan"/&gt;
 *     &lt;enumeration value="canTilt"/&gt;
 *     &lt;enumeration value="canZoom"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TrafficCameraCapabilityEnum")
@XmlEnum
public enum TrafficCameraCapabilityEnum {


    /**
     * Camera supports pan
     * 
     */
    @XmlEnumValue("canPan")
    CAN_PAN("canPan"),

    /**
     * Camera supports tilt
     * 
     */
    @XmlEnumValue("canTilt")
    CAN_TILT("canTilt"),

    /**
     * Camera supports zoom
     * 
     */
    @XmlEnumValue("canZoom")
    CAN_ZOOM("canZoom");
    private final String value;

    TrafficCameraCapabilityEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TrafficCameraCapabilityEnum fromValue(String v) {
        for (TrafficCameraCapabilityEnum c: TrafficCameraCapabilityEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
