//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.17 at 06:36:56 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://datex2.eu/schema/2/2_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.projektr.tomcatservertest;
